/**
 * @fileoverview Repository for managing delivery data access operations.
 * 
 * This module provides data access methods for delivery entities in the OctoCAT supply chain system.
 * Deliveries represent shipments from suppliers to branches, tracking the physical movement of goods.
 * Each delivery is associated with a supplier, contains tracking information, status updates, and
 * expected/actual delivery dates. Individual items within a delivery are managed through
 * OrderDetailDelivery join records.
 * 
 * The repository implements standard CRUD operations plus specialized queries for:
 * - Finding deliveries by supplier for vendor performance tracking
 * - Filtering deliveries by status (pending, in_transit, delivered, cancelled)
 * - Querying deliveries within date ranges for logistics planning
 * - Managing delivery lifecycle and tracking updates
 * 
 * @module repositories/deliveriesRepo
 */

import { getDatabase, DatabaseConnection } from '../db/sqlite';
import { Delivery } from '../models/delivery';
import { handleDatabaseError, NotFoundError } from '../utils/errors';
import { buildInsertSQL, buildUpdateSQL, objectToCamelCase, mapDatabaseRows, DatabaseRow } from '../utils/sql';

export class DeliveriesRepository {
  private db: DatabaseConnection;

  constructor(db: DatabaseConnection) {
    this.db = db;
  }

  /**
   * Retrieves all deliveries from the database.
   * 
   * Returns deliveries ordered by their unique identifier for consistent pagination.
   * This method is typically used for administrative dashboards showing comprehensive
   * delivery tracking and logistics overview.
   * 
   * @returns Promise resolving to an array of all delivery records
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * const deliveries = await repo.findAll();
   * console.log(`Total deliveries tracked: ${deliveries.length}`);
   * // Output: Total deliveries tracked: 856
   * ```
   */
  async findAll(): Promise<Delivery[]> {
    try {
      const rows = await this.db.all<DatabaseRow>('SELECT * FROM deliveries ORDER BY delivery_id');
      return mapDatabaseRows<Delivery>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves a single delivery by its unique identifier.
   * 
   * Primary lookup method for fetching delivery details when you have the delivery ID
   * from a tracking number, URL parameter, or order detail delivery reference.
   * 
   * @param id - The unique identifier of the delivery to retrieve
   * @returns Promise resolving to the delivery object if found, null otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * const delivery = await repo.findById(301);
   * if (delivery) {
   *   console.log(`Delivery #${delivery.deliveryId}: ${delivery.status}`);
   *   console.log(`Tracking: ${delivery.trackingNumber}`);
   *   // Output: Delivery #301: in_transit
   *   // Output: Tracking: TRACK-2024-020601
   * }
   * ```
   */
  async findById(id: number): Promise<Delivery | null> {
    try {
      const row = await this.db.get<DatabaseRow>('SELECT * FROM deliveries WHERE delivery_id = ?', [id]);
      return row ? objectToCamelCase<Delivery>(row) : null;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Creates a new delivery in the database.
   * 
   * Inserts a new delivery record with supplier association, tracking information,
   * and delivery dates. The delivery ID is auto-generated by the database. Typically
   * followed by creating OrderDetailDelivery records to link specific order line items.
   * 
   * @param delivery - Delivery data without the deliveryId (auto-generated)
   * @returns Promise resolving to the newly created delivery with generated ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If required fields are missing or invalid
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * const newDelivery = await repo.create({
   *   supplierId: 5,
   *   trackingNumber: 'TRACK-2024-020602',
   *   deliveryDate: '2024-02-06',
   *   status: 'pending',
   *   expectedDeliveryDate: '2024-02-10',
   *   notes: 'Expedited shipping requested'
   * });
   * console.log(`Created delivery #${newDelivery.deliveryId}`);
   * ```
   */
  async create(delivery: Omit<Delivery, 'deliveryId'>): Promise<Delivery> {
    try {
      const { sql, values } = buildInsertSQL('deliveries', delivery);
      const result = await this.db.run(sql, values);

      const createdDelivery = await this.findById(result.lastID || 0);
      if (!createdDelivery) {
        throw new Error('Failed to retrieve created delivery');
      }

      return createdDelivery;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Updates an existing delivery with partial data.
   * 
   * Allows updating specific fields of a delivery without requiring all fields.
   * Commonly used for status updates, adding tracking notes, and updating delivery dates.
   * The delivery ID cannot be modified.
   * 
   * @param id - The unique identifier of the delivery to update
   * @param delivery - Partial delivery data containing only the fields to update
   * @returns Promise resolving to the updated delivery object
   * @throws {NotFoundError} If no delivery exists with the given ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If update data contains invalid values
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * const updated = await repo.update(301, {
   *   status: 'delivered',
   *   notes: 'Delivered to receiving dock, signed by warehouse manager'
   * });
   * console.log(`Delivery #${updated.deliveryId} marked as ${updated.status}`);
   * ```
   */
  async update(id: number, delivery: Partial<Omit<Delivery, 'deliveryId'>>): Promise<Delivery> {
    try {
      const { sql, values } = buildUpdateSQL('deliveries', delivery, 'delivery_id = ?');
      const result = await this.db.run(sql, [...values, id]);

      if (result.changes === 0) {
        throw new NotFoundError('Delivery', id);
      }

      const updatedDelivery = await this.findById(id);
      if (!updatedDelivery) {
        throw new Error('Failed to retrieve updated delivery');
      }

      return updatedDelivery;
    } catch (error) {
      handleDatabaseError(error, 'Delivery', id);
    }
  }

  /**
   * Deletes a delivery from the database.
   * 
   * Permanently removes the delivery record. This will fail if the delivery has
   * associated OrderDetailDelivery records due to foreign key constraints. In production,
   * consider using status='cancelled' instead of physical deletion for audit purposes.
   * 
   * @param id - The unique identifier of the delivery to delete
   * @returns Promise that resolves when deletion is complete
   * @throws {NotFoundError} If no delivery exists with the given ID
   * @throws {DatabaseError} If deletion fails (e.g., has associated order details)
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * await repo.delete(999);
   * console.log('Delivery record deleted successfully');
   * ```
   */
  async delete(id: number): Promise<void> {
    try {
      const result = await this.db.run('DELETE FROM deliveries WHERE delivery_id = ?', [id]);

      if (result.changes === 0) {
        throw new NotFoundError('Delivery', id);
      }
    } catch (error) {
      handleDatabaseError(error, 'Delivery', id);
    }
  }

  /**
   * Checks whether a delivery exists in the database.
   * 
   * Efficient existence check using COUNT query. Useful for validating delivery
   * references before creating order detail delivery links or processing receipts.
   * 
   * @param id - The unique identifier of the delivery to check
   * @returns Promise resolving to true if delivery exists, false otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * const deliveryExists = await repo.exists(301);
   * if (!deliveryExists) {
   *   console.log('Delivery not found, cannot record receipt');
   * }
   * ```
   */
  async exists(id: number): Promise<boolean> {
    try {
      const result = await this.db.get<{ count: number }>(
        'SELECT COUNT(*) as count FROM deliveries WHERE delivery_id = ?',
        [id],
      );
      return (result?.count || 0) > 0;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves all deliveries from a specific supplier.
   * 
   * Returns deliveries sorted by date (most recent first). This method is essential for
   * supplier performance tracking, analyzing delivery patterns, and managing vendor
   * relationships.
   * 
   * @param supplierId - The unique identifier of the supplier
   * @returns Promise resolving to an array of deliveries from the supplier
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * const acmeDeliveries = await repo.findBySupplierId(5);
   * console.log(`ACME Corp has made ${acmeDeliveries.length} deliveries`);
   * const onTimeCount = acmeDeliveries.filter(d => d.status === 'delivered').length;
   * console.log(`On-time delivery rate: ${(onTimeCount/acmeDeliveries.length*100).toFixed(1)}%`);
   * ```
   */
  async findBySupplierId(supplierId: number): Promise<Delivery[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM deliveries WHERE supplier_id = ? ORDER BY delivery_date DESC',
        [supplierId],
      );
      return mapDatabaseRows<Delivery>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves all deliveries with a specific status.
   * 
   * Returns deliveries sorted by date (most recent first). Useful for logistics dashboards,
   * tracking in-transit shipments, and managing receiving operations. Common statuses include:
   * pending, in_transit, delivered, cancelled.
   * 
   * @param status - The delivery status to filter by
   * @returns Promise resolving to an array of deliveries with the specified status
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * const inTransit = await repo.findByStatus('in_transit');
   * console.log(`${inTransit.length} deliveries currently in transit`);
   * inTransit.forEach(d => {
   *   console.log(`- Tracking: ${d.trackingNumber}, ETA: ${d.expectedDeliveryDate}`);
   * });
   * ```
   */
  async findByStatus(status: string): Promise<Delivery[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM deliveries WHERE status = ? ORDER BY delivery_date DESC',
        [status],
      );
      return mapDatabaseRows<Delivery>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves all deliveries within a specific date range.
   * 
   * Returns deliveries sorted by date (most recent first). Essential for generating
   * logistics reports, analyzing delivery patterns, and reconciling shipments.
   * Date parameters should be in ISO format (YYYY-MM-DD).
   * 
   * @param startDate - The start of the date range (inclusive, ISO format)
   * @param endDate - The end of the date range (inclusive, ISO format)
   * @returns Promise resolving to an array of deliveries within the date range
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * const februaryDeliveries = await repo.findByDateRange('2024-02-01', '2024-02-29');
   * console.log(`February had ${februaryDeliveries.length} deliveries`);
   * // Output: February had 143 deliveries
   * ```
   */
  async findByDateRange(startDate: string, endDate: string): Promise<Delivery[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM deliveries WHERE delivery_date >= ? AND delivery_date <= ? ORDER BY delivery_date DESC',
        [startDate, endDate],
      );
      return mapDatabaseRows<Delivery>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Updates the status of a delivery.
   * 
   * Convenience method for status-only updates, which is the most common delivery
   * update operation. Internally calls the update method with status field.
   * 
   * @param id - The unique identifier of the delivery to update
   * @param status - The new status value to set
   * @returns Promise resolving to the updated delivery object
   * @throws {NotFoundError} If no delivery exists with the given ID
   * @throws {DatabaseError} If the database operation fails
   * 
   * @example
   * ```typescript
   * const repo = await createDeliveriesRepository();
   * const updated = await repo.updateStatus(301, 'delivered');
   * console.log(`Delivery #${updated.deliveryId} status: ${updated.status}`);
   * // Output: Delivery #301 status: delivered
   * ```
   */
  async updateStatus(id: number, status: string): Promise<Delivery> {
    try {
      return await this.update(id, { status });
    } catch (error) {
      handleDatabaseError(error, 'Delivery', id);
    }
  }
}

/**
 * Factory function to create a new DeliveriesRepository instance.
 * 
 * Creates a repository connected to the appropriate database (production or test).
 * Each call creates a new instance; use this when you need isolated repository instances.
 * 
 * @param isTest - Whether to use the test database (default: false)
 * @returns Promise resolving to a new DeliveriesRepository instance
 * 
 * @example
 * ```typescript
 * // Production usage
 * const repo = await createDeliveriesRepository();
 * 
 * // Test usage
 * const testRepo = await createDeliveriesRepository(true);
 * ```
 */
export async function createDeliveriesRepository(
  isTest: boolean = false,
): Promise<DeliveriesRepository> {
  const db = await getDatabase(isTest);
  return new DeliveriesRepository(db);
}

// Singleton instance for default usage
let deliveriesRepo: DeliveriesRepository | null = null;

/**
 * Retrieves the DeliveriesRepository instance.
 * 
 * Returns a cached repository instance for production use, or creates a new test instance
 * when in test mode. This provides efficient resource usage by reusing database connections.
 * 
 * @param isTest - Whether to use the test database (default: false)
 * @returns Promise resolving to the DeliveriesRepository instance
 * 
 * @example
 * ```typescript
 * // Get shared production instance
 * const repo = await getDeliveriesRepository();
 * 
 * // Get new test instance
 * const testRepo = await getDeliveriesRepository(true);
 * ```
 */
export async function getDeliveriesRepository(
  isTest: boolean = false,
): Promise<DeliveriesRepository> {
  const isTestEnv = isTest || process.env.NODE_ENV === 'test' || process.env.VITEST === 'true';
  if (isTestEnv) {
    return createDeliveriesRepository(true);
  }
  if (!deliveriesRepo) {
    deliveriesRepo = await createDeliveriesRepository(false);
  }
  return deliveriesRepo;
}
