/**
 * @fileoverview Repository for managing headquarters data access operations.
 * 
 * This module provides data access methods for headquarters entities in the OctoCAT supply chain system.
 * Headquarters represent the main corporate offices or regional command centers that oversee multiple
 * branches. Each headquarters manages supplier relationships, coordinates multi-branch operations,
 * and maintains strategic inventory levels.
 * 
 * The repository implements standard CRUD operations plus specialized queries for:
 * - Searching headquarters by name patterns
 * - Validating headquarters existence
 * - Managing organizational hierarchy
 * 
 * @module repositories/headquartersRepo
 */

import { getDatabase, DatabaseConnection } from '../db/sqlite';
import { Headquarters } from '../models/headquarters';
import { handleDatabaseError, NotFoundError } from '../utils/errors';
import { buildInsertSQL, buildUpdateSQL, objectToCamelCase, mapDatabaseRows, DatabaseRow } from '../utils/sql';

export class HeadquartersRepository {
  private db: DatabaseConnection;

  constructor(db: DatabaseConnection) {
    this.db = db;
  }

  /**
   * Retrieves all headquarters from the database.
   * 
   * Returns headquarters ordered by their unique identifier for consistent pagination
   * and display. This method is typically used for administrative dashboards showing
   * the complete organizational structure.
   * 
   * @returns Promise resolving to an array of all headquarters records
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createHeadquartersRepository();
   * const allHQ = await repo.findAll();
   * console.log(`Organization has ${allHQ.length} headquarters`);
   * // Output: Organization has 3 headquarters
   * ```
   */
  async findAll(): Promise<Headquarters[]> {
    try {
      const rows = await this.db.all<DatabaseRow>('SELECT * FROM headquarters ORDER BY headquarters_id');
      return mapDatabaseRows<Headquarters>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves a single headquarters by its unique identifier.
   * 
   * Primary lookup method for fetching headquarters details when you have the ID
   * from a URL parameter, foreign key relationship, or stored reference.
   * 
   * @param id - The unique identifier of the headquarters to retrieve
   * @returns Promise resolving to the headquarters object if found, null otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createHeadquartersRepository();
   * const hq = await repo.findById(1);
   * if (hq) {
   *   console.log(`${hq.name} located in ${hq.city}, ${hq.state}`);
   *   // Output: West Coast Operations located in Seattle, WA
   * }
   * ```
   */
  async findById(id: number): Promise<Headquarters | null> {
    try {
      const row = await this.db.get<DatabaseRow>('SELECT * FROM headquarters WHERE headquarters_id = ?', [
        id,
      ]);
      return row ? objectToCamelCase<Headquarters>(row) : null;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Creates a new headquarters in the database.
   * 
   * Inserts a new headquarters record with all required fields. The headquarters ID
   * is auto-generated by the database. After creation, the method retrieves and returns
   * the complete headquarters object including the generated ID.
   * 
   * @param headquarters - Headquarters data without the headquartersId (auto-generated)
   * @returns Promise resolving to the newly created headquarters with generated ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If required fields are missing or invalid
   * 
   * @example
   * ```typescript
   * const repo = await createHeadquartersRepository();
   * const newHQ = await repo.create({
   *   name: 'East Coast Operations',
   *   address: '100 Business Plaza',
   *   city: 'New York',
   *   state: 'NY',
   *   zipCode: '10001',
   *   phone: '212-555-0100',
   *   email: 'east.coast@octocat.com'
   * });
   * console.log(`Created HQ with ID: ${newHQ.headquartersId}`);
   * ```
   */
  async create(headquarters: Omit<Headquarters, 'headquartersId'>): Promise<Headquarters> {
    try {
      const { sql, values } = buildInsertSQL('headquarters', headquarters);
      const result = await this.db.run(sql, values);

      const createdHeadquarters = await this.findById(result.lastID || 0);
      if (!createdHeadquarters) {
        throw new Error('Failed to retrieve created headquarters');
      }

      return createdHeadquarters;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Updates an existing headquarters with partial data.
   * 
   * Allows updating specific fields of a headquarters without requiring all fields.
   * Only the provided fields will be updated; others remain unchanged. The headquarters
   * ID cannot be modified.
   * 
   * @param id - The unique identifier of the headquarters to update
   * @param headquarters - Partial headquarters data containing only the fields to update
   * @returns Promise resolving to the updated headquarters object
   * @throws {NotFoundError} If no headquarters exists with the given ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If update data contains invalid values
   * 
   * @example
   * ```typescript
   * const repo = await createHeadquartersRepository();
   * const updated = await repo.update(1, {
   *   phone: '206-555-0150',
   *   email: 'west.coast.updated@octocat.com'
   * });
   * console.log(`Updated contact info for ${updated.name}`);
   * ```
   */
  async update(
    id: number,
    headquarters: Partial<Omit<Headquarters, 'headquartersId'>>,
  ): Promise<Headquarters> {
    try {
      const { sql, values } = buildUpdateSQL('headquarters', headquarters, 'headquarters_id = ?');
      const result = await this.db.run(sql, [...values, id]);

      if (result.changes === 0) {
        throw new NotFoundError('Headquarters', id);
      }

      const updatedHeadquarters = await this.findById(id);
      if (!updatedHeadquarters) {
        throw new Error('Failed to retrieve updated headquarters');
      }

      return updatedHeadquarters;
    } catch (error) {
      handleDatabaseError(error, 'Headquarters', id);
    }
  }

  /**
   * Deletes a headquarters from the database.
   * 
   * Permanently removes the headquarters record. This operation will typically fail
   * if the headquarters has associated branches due to foreign key constraints.
   * Consider implementing soft deletes for production environments.
   * 
   * @param id - The unique identifier of the headquarters to delete
   * @returns Promise that resolves when deletion is complete
   * @throws {NotFoundError} If no headquarters exists with the given ID
   * @throws {DatabaseError} If deletion fails (e.g., has associated branches)
   * 
   * @example
   * ```typescript
   * const repo = await createHeadquartersRepository();
   * await repo.delete(99);
   * console.log('Headquarters deleted successfully');
   * ```
   */
  async delete(id: number): Promise<void> {
    try {
      const result = await this.db.run('DELETE FROM headquarters WHERE headquarters_id = ?', [id]);

      if (result.changes === 0) {
        throw new NotFoundError('Headquarters', id);
      }
    } catch (error) {
      handleDatabaseError(error, 'Headquarters', id);
    }
  }

  /**
   * Checks whether a headquarters exists in the database.
   * 
   * Efficient existence check using COUNT query. Useful for validation before
   * creating branches or establishing organizational relationships.
   * 
   * @param id - The unique identifier of the headquarters to check
   * @returns Promise resolving to true if headquarters exists, false otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createHeadquartersRepository();
   * const hqExists = await repo.exists(1);
   * if (!hqExists) {
   *   console.log('Headquarters not found, cannot create branch');
   * }
   * ```
   */
  async exists(id: number): Promise<boolean> {
    try {
      const result = await this.db.get<{ count: number }>(
        'SELECT COUNT(*) as count FROM headquarters WHERE headquarters_id = ?',
        [id],
      );
      return (result?.count || 0) > 0;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Searches for headquarters by name using partial matching.
   * 
   * Performs a case-insensitive LIKE query to find headquarters whose names contain
   * the search term. Results are ordered alphabetically. Useful for autocomplete,
   * search functionality, and filtering organizational views.
   * 
   * @param name - Search term to match against headquarters names (case-insensitive)
   * @returns Promise resolving to an array of matching headquarters
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createHeadquartersRepository();
   * const coastHQs = await repo.findByName('Coast');
   * console.log(`Found ${coastHQs.length} coast headquarters`);
   * // Matches: 'West Coast Operations', 'East Coast Operations'
   * ```
   */
  async findByName(name: string): Promise<Headquarters[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM headquarters WHERE name LIKE ? ORDER BY name',
        [`%${name}%`],
      );
      return mapDatabaseRows<Headquarters>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }
}

/**
 * Factory function to create a new HeadquartersRepository instance.
 * 
 * Creates a repository connected to the appropriate database (production or test).
 * Each call creates a new instance; use this when you need isolated repository instances.
 * 
 * @param isTest - Whether to use the test database (default: false)
 * @returns Promise resolving to a new HeadquartersRepository instance
 * 
 * @example
 * ```typescript
 * // Production usage
 * const repo = await createHeadquartersRepository();
 * 
 * // Test usage
 * const testRepo = await createHeadquartersRepository(true);
 * ```
 */
export async function createHeadquartersRepository(
  isTest: boolean = false,
): Promise<HeadquartersRepository> {
  const db = await getDatabase(isTest);
  return new HeadquartersRepository(db);
}

// Singleton instance for default usage
let headquartersRepo: HeadquartersRepository | null = null;

/**
 * Retrieves the singleton HeadquartersRepository instance.
 * 
 * Returns a cached repository instance for production use, or creates a new test instance
 * when in test mode. This provides efficient resource usage by reusing database connections.
 * 
 * @param isTest - Whether to use the test database (default: false)
 * @returns Promise resolving to the HeadquartersRepository instance
 * 
 * @example
 * ```typescript
 * // Get shared production instance
 * const repo = await getHeadquartersRepository();
 * 
 * // Get new test instance
 * const testRepo = await getHeadquartersRepository(true);
 * ```
 */
export async function getHeadquartersRepository(
  isTest: boolean = false,
): Promise<HeadquartersRepository> {
  if (!headquartersRepo) {
    headquartersRepo = await createHeadquartersRepository(isTest);
  }
  return headquartersRepo;
}
