/**
 * @fileoverview Repository for managing order detail data access operations.
 * 
 * This module provides data access methods for order detail entities in the OctoCAT supply chain system.
 * Order details represent individual line items within an order, containing product references,
 * quantities, and pricing information. Each order detail belongs to a parent order and references
 * a specific product.
 * 
 * The repository implements standard CRUD operations plus specialized queries for:
 * - Finding all line items for a specific order
 * - Retrieving all orders containing a specific product
 * - Calculating total order values from line items
 * - Managing order composition and fulfillment tracking
 * 
 * @module repositories/orderDetailsRepo
 */

import { getDatabase, DatabaseConnection } from '../db/sqlite';
import { OrderDetail } from '../models/orderDetail';
import { handleDatabaseError, NotFoundError } from '../utils/errors';
import { buildInsertSQL, buildUpdateSQL, objectToCamelCase, mapDatabaseRows, DatabaseRow } from '../utils/sql';

export class OrderDetailsRepository {
  private db: DatabaseConnection;

  constructor(db: DatabaseConnection) {
    this.db = db;
  }

  /**
   * Retrieves all order details from the database.
   * 
   * Returns order details ordered by their unique identifier. This method is primarily
   * used for administrative reporting and system-wide analytics. For most use cases,
   * prefer querying by orderId or productId.
   * 
   * @returns Promise resolving to an array of all order detail records
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrderDetailsRepository();
   * const allDetails = await repo.findAll();
   * console.log(`Total line items in system: ${allDetails.length}`);
   * // Output: Total line items in system: 4,872
   * ```
   */
  async findAll(): Promise<OrderDetail[]> {
    try {
      const rows = await this.db.all<DatabaseRow>('SELECT * FROM order_details ORDER BY order_detail_id');
      return mapDatabaseRows<OrderDetail>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves a single order detail by its unique identifier.
   * 
   * Primary lookup method for fetching specific line item details when you have
   * the order detail ID from a delivery record or direct reference.
   * 
   * @param id - The unique identifier of the order detail to retrieve
   * @returns Promise resolving to the order detail object if found, null otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrderDetailsRepository();
   * const detail = await repo.findById(501);
   * if (detail) {
   *   console.log(`Line item: ${detail.quantity} units @ $${detail.unitPrice}`);
   *   // Output: Line item: 50 units @ $29.99
   * }
   * ```
   */
  async findById(id: number): Promise<OrderDetail | null> {
    try {
      const row = await this.db.get<DatabaseRow>('SELECT * FROM order_details WHERE order_detail_id = ?', [
        id,
      ]);
      return row ? objectToCamelCase<OrderDetail>(row) : null;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Creates a new order detail (line item) in the database.
   * 
   * Inserts a new line item record linking an order to a product with quantity
   * and pricing information. The order detail ID is auto-generated by the database.
   * This method is called when adding products to an order.
   * 
   * @param orderDetail - Order detail data without the orderDetailId (auto-generated)
   * @returns Promise resolving to the newly created order detail with generated ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If required fields are missing or invalid
   * 
   * @example
   * ```typescript
   * const repo = await createOrderDetailsRepository();
   * const lineItem = await repo.create({
   *   orderId: 1001,
   *   productId: 42,
   *   quantity: 50,
   *   unitPrice: 29.99
   * });
   * console.log(`Added line item #${lineItem.orderDetailId} to order`);
   * ```
   */
  async create(orderDetail: Omit<OrderDetail, 'orderDetailId'>): Promise<OrderDetail> {
    try {
      const { sql, values } = buildInsertSQL('order_details', orderDetail);
      const result = await this.db.run(sql, values);

      const createdOrderDetail = await this.findById(result.lastID || 0);
      if (!createdOrderDetail) {
        throw new Error('Failed to retrieve created order detail');
      }

      return createdOrderDetail;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Updates an existing order detail with partial data.
   * 
   * Allows updating specific fields of a line item without requiring all fields.
   * Commonly used for quantity adjustments or price corrections. The order detail ID
   * cannot be modified.
   * 
   * @param id - The unique identifier of the order detail to update
   * @param orderDetail - Partial order detail data containing only the fields to update
   * @returns Promise resolving to the updated order detail object
   * @throws {NotFoundError} If no order detail exists with the given ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If update data contains invalid values
   * 
   * @example
   * ```typescript
   * const repo = await createOrderDetailsRepository();
   * const updated = await repo.update(501, {
   *   quantity: 75,
   *   unitPrice: 27.99
   * });
   * console.log(`Updated quantity to ${updated.quantity}`);
   * ```
   */
  async update(
    id: number,
    orderDetail: Partial<Omit<OrderDetail, 'orderDetailId'>>,
  ): Promise<OrderDetail> {
    try {
      const { sql, values } = buildUpdateSQL('order_details', orderDetail, 'order_detail_id = ?');
      const result = await this.db.run(sql, [...values, id]);

      if (result.changes === 0) {
        throw new NotFoundError('OrderDetail', id);
      }

      const updatedOrderDetail = await this.findById(id);
      if (!updatedOrderDetail) {
        throw new Error('Failed to retrieve updated order detail');
      }

      return updatedOrderDetail;
    } catch (error) {
      handleDatabaseError(error, 'OrderDetail', id);
    }
  }

  /**
   * Deletes an order detail from the database.
   * 
   * Permanently removes the line item record. This may fail if the order detail has
   * associated delivery records due to foreign key constraints. Use with caution as
   * this affects order totals and history.
   * 
   * @param id - The unique identifier of the order detail to delete
   * @returns Promise that resolves when deletion is complete
   * @throws {NotFoundError} If no order detail exists with the given ID
   * @throws {DatabaseError} If deletion fails (e.g., has delivery records)
   * 
   * @example
   * ```typescript
   * const repo = await createOrderDetailsRepository();
   * await repo.delete(999);
   * console.log('Line item removed from order');
   * ```
   */
  async delete(id: number): Promise<void> {
    try {
      const result = await this.db.run('DELETE FROM order_details WHERE order_detail_id = ?', [id]);

      if (result.changes === 0) {
        throw new NotFoundError('OrderDetail', id);
      }
    } catch (error) {
      handleDatabaseError(error, 'OrderDetail', id);
    }
  }

  /**
   * Checks whether an order detail exists in the database.
   * 
   * Efficient existence check using COUNT query. Useful for validating line item
   * references before creating delivery records or processing fulfillment.
   * 
   * @param id - The unique identifier of the order detail to check
   * @returns Promise resolving to true if order detail exists, false otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrderDetailsRepository();
   * const itemExists = await repo.exists(501);
   * if (!itemExists) {
   *   console.log('Line item not found, cannot record delivery');
   * }
   * ```
   */
  async exists(id: number): Promise<boolean> {
    try {
      const result = await this.db.get<{ count: number }>(
        'SELECT COUNT(*) as count FROM order_details WHERE order_detail_id = ?',
        [id],
      );
      return (result?.count || 0) > 0;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves all line items for a specific order.
   * 
   * Returns order details in the order they were created. This is the most commonly
   * used query method, essential for displaying order contents, calculating totals,
   * and managing fulfillment.
   * 
   * @param orderId - The unique identifier of the order
   * @returns Promise resolving to an array of order details for the order
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrderDetailsRepository();
   * const items = await repo.findByOrderId(1001);
   * console.log(`Order #1001 contains ${items.length} line items`);
   * items.forEach(item => {
   *   console.log(`- Product ${item.productId}: ${item.quantity} @ $${item.unitPrice}`);
   * });
   * ```
   */
  async findByOrderId(orderId: number): Promise<OrderDetail[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM order_details WHERE order_id = ? ORDER BY order_detail_id',
        [orderId],
      );
      return mapDatabaseRows<OrderDetail>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves all order line items containing a specific product.
   * 
   * Returns order details showing all historical orders that included this product.
   * Useful for analyzing product demand, tracking product sales history, and
   * generating product-specific reports.
   * 
   * @param productId - The unique identifier of the product
   * @returns Promise resolving to an array of order details containing the product
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrderDetailsRepository();
   * const productOrders = await repo.findByProductId(42);
   * console.log(`Product #42 appears in ${productOrders.length} orders`);
   * const totalQty = productOrders.reduce((sum, d) => sum + d.quantity, 0);
   * console.log(`Total quantity ordered: ${totalQty} units`);
   * ```
   */
  async findByProductId(productId: number): Promise<OrderDetail[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM order_details WHERE product_id = ? ORDER BY order_detail_id',
        [productId],
      );
      return mapDatabaseRows<OrderDetail>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Calculates the total value of all line items for a specific order.
   * 
   * Computes the sum of (quantity × unitPrice) for all order details belonging to
   * the specified order. Returns 0 if the order has no line items. Essential for
   * displaying order totals, invoicing, and financial reporting.
   * 
   * @param orderId - The unique identifier of the order
   * @returns Promise resolving to the total order value as a number
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrderDetailsRepository();
   * const total = await repo.getTotalValueByOrderId(1001);
   * console.log(`Order #1001 total: $${total.toFixed(2)}`);
   * // Output: Order #1001 total: $4,237.50
   * ```
   */
  async getTotalValueByOrderId(orderId: number): Promise<number> {
    try {
      const result = await this.db.get<{ total: number }>(
        'SELECT SUM(quantity * unit_price) as total FROM order_details WHERE order_id = ?',
        [orderId],
      );
      return result?.total || 0;
    } catch (error) {
      handleDatabaseError(error);
    }
  }
}

/**
 * Factory function to create a new OrderDetailsRepository instance.
 * 
 * Creates a repository connected to the appropriate database (production or test).
 * Each call creates a new instance; use this when you need isolated repository instances.
 * 
 * @param isTest - Whether to use the test database (default: false)
 * @returns Promise resolving to a new OrderDetailsRepository instance
 * 
 * @example
 * ```typescript
 * // Production usage
 * const repo = await createOrderDetailsRepository();
 * 
 * // Test usage
 * const testRepo = await createOrderDetailsRepository(true);
 * ```
 */
export async function createOrderDetailsRepository(
  isTest: boolean = false,
): Promise<OrderDetailsRepository> {
  const db = await getDatabase(isTest);
  return new OrderDetailsRepository(db);
}

// Singleton instance for default usage
let orderDetailsRepo: OrderDetailsRepository | null = null;

/**
 * Retrieves the singleton OrderDetailsRepository instance.
 * 
 * Returns a cached repository instance for production use. This provides efficient
 * resource usage by reusing database connections across multiple calls.
 * 
 * @param isTest - Whether to use the test database (default: false)
 * @returns Promise resolving to the OrderDetailsRepository instance
 * 
 * @example
 * ```typescript
 * // Get shared production instance
 * const repo = await getOrderDetailsRepository();
 * 
 * // Get test instance
 * const testRepo = await getOrderDetailsRepository(true);
 * ```
 */
export async function getOrderDetailsRepository(
  isTest: boolean = false,
): Promise<OrderDetailsRepository> {
  if (!orderDetailsRepo) {
    orderDetailsRepo = await createOrderDetailsRepository(isTest);
  }
  return orderDetailsRepo;
}
