/**
 * @fileoverview Repository for managing order data access operations.
 * 
 * This module provides data access methods for order entities in the OctoCAT supply chain system.
 * Orders represent purchase requests placed by branches for products from suppliers. Each order
 * contains header-level information including the ordering branch, order date, status, and
 * expected delivery date. Individual line items are managed through OrderDetail entities.
 * 
 * The repository implements standard CRUD operations plus specialized queries for:
 * - Finding orders by branch for location-specific order history
 * - Filtering orders by status (pending, approved, shipped, delivered, cancelled)
 * - Querying orders within date ranges for reporting and analytics
 * - Managing order lifecycle and fulfillment tracking
 * 
 * @module repositories/ordersRepo
 */

import { getDatabase, DatabaseConnection } from '../db/sqlite';
import { Order } from '../models/order';
import { handleDatabaseError, NotFoundError } from '../utils/errors';
import { buildInsertSQL, buildUpdateSQL, objectToCamelCase, mapDatabaseRows, DatabaseRow } from '../utils/sql';

export class OrdersRepository {
  private db: DatabaseConnection;

  constructor(db: DatabaseConnection) {
    this.db = db;
  }

  /**
   * Retrieves all orders from the database.
   * 
   * Returns orders ordered by their unique identifier for consistent pagination.
   * This method is typically used for administrative dashboards, comprehensive
   * order reports, and system-wide order analytics.
   * 
   * @returns Promise resolving to an array of all order records
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrdersRepository();
   * const orders = await repo.findAll();
   * console.log(`Total orders in system: ${orders.length}`);
   * // Output: Total orders in system: 1,523
   * ```
   */
  async findAll(): Promise<Order[]> {
    try {
      const rows = await this.db.all<DatabaseRow>('SELECT * FROM orders ORDER BY order_id');
      return mapDatabaseRows<Order>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves a single order by its unique identifier.
   * 
   * Primary lookup method for fetching order details when you have the order ID
   * from a URL parameter, workflow reference, or order confirmation.
   * 
   * @param id - The unique identifier of the order to retrieve
   * @returns Promise resolving to the order object if found, null otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrdersRepository();
   * const order = await repo.findById(1001);
   * if (order) {
   *   console.log(`Order #${order.orderId}: ${order.status} (${order.orderDate})`);
   *   // Output: Order #1001: shipped (2024-01-15)
   * }
   * ```
   */
  async findById(id: number): Promise<Order | null> {
    try {
      const row = await this.db.get<DatabaseRow>('SELECT * FROM orders WHERE order_id = ?', [id]);
      return row ? objectToCamelCase<Order>(row) : null;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Creates a new order in the database.
   * 
   * Inserts a new order record with branch association, dates, and initial status.
   * The order ID is auto-generated by the database. Typically followed by creating
   * associated order detail records for the line items.
   * 
   * @param order - Order data without the orderId (auto-generated)
   * @returns Promise resolving to the newly created order with generated ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If required fields are missing or invalid
   * 
   * @example
   * ```typescript
   * const repo = await createOrdersRepository();
   * const newOrder = await repo.create({
   *   branchId: 5,
   *   orderDate: '2024-02-06',
   *   status: 'pending',
   *   expectedDeliveryDate: '2024-02-13',
   *   notes: 'Rush order for new product launch'
   * });
   * console.log(`Created order #${newOrder.orderId}`);
   * ```
   */
  async create(order: Omit<Order, 'orderId'>): Promise<Order> {
    try {
      const { sql, values } = buildInsertSQL('orders', order);
      const result = await this.db.run(sql, values);

      const createdOrder = await this.findById(result.lastID || 0);
      if (!createdOrder) {
        throw new Error('Failed to retrieve created order');
      }

      return createdOrder;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Updates an existing order with partial data.
   * 
   * Allows updating specific fields of an order without requiring all fields.
   * Commonly used for status updates, delivery date changes, and adding notes.
   * The order ID cannot be modified.
   * 
   * @param id - The unique identifier of the order to update
   * @param order - Partial order data containing only the fields to update
   * @returns Promise resolving to the updated order object
   * @throws {NotFoundError} If no order exists with the given ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If update data contains invalid values
   * 
   * @example
   * ```typescript
   * const repo = await createOrdersRepository();
   * const updated = await repo.update(1001, {
   *   status: 'delivered',
   *   notes: 'Delivered to loading dock, signed by J. Smith'
   * });
   * console.log(`Order #${updated.orderId} marked as ${updated.status}`);
   * ```
   */
  async update(id: number, order: Partial<Omit<Order, 'orderId'>>): Promise<Order> {
    try {
      const { sql, values } = buildUpdateSQL('orders', order, 'order_id = ?');
      const result = await this.db.run(sql, [...values, id]);

      if (result.changes === 0) {
        throw new NotFoundError('Order', id);
      }

      const updatedOrder = await this.findById(id);
      if (!updatedOrder) {
        throw new Error('Failed to retrieve updated order');
      }

      return updatedOrder;
    } catch (error) {
      handleDatabaseError(error, 'Order', id);
    }
  }

  /**
   * Deletes an order from the database.
   * 
   * Permanently removes the order record. This will typically fail if the order has
   * associated order details due to foreign key constraints. In production, consider
   * using status='cancelled' instead of physical deletion for audit trail purposes.
   * 
   * @param id - The unique identifier of the order to delete
   * @returns Promise that resolves when deletion is complete
   * @throws {NotFoundError} If no order exists with the given ID
   * @throws {DatabaseError} If deletion fails (e.g., has order details)
   * 
   * @example
   * ```typescript
   * const repo = await createOrdersRepository();
   * await repo.delete(9999);
   * console.log('Order deleted successfully');
   * ```
   */
  async delete(id: number): Promise<void> {
    try {
      const result = await this.db.run('DELETE FROM orders WHERE order_id = ?', [id]);

      if (result.changes === 0) {
        throw new NotFoundError('Order', id);
      }
    } catch (error) {
      handleDatabaseError(error, 'Order', id);
    }
  }

  /**
   * Checks whether an order exists in the database.
   * 
   * Efficient existence check using COUNT query. Useful for validating order
   * references before creating related entities or processing workflows.
   * 
   * @param id - The unique identifier of the order to check
   * @returns Promise resolving to true if order exists, false otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrdersRepository();
   * const orderExists = await repo.exists(1001);
   * if (!orderExists) {
   *   console.log('Order not found, cannot add line items');
   * }
   * ```
   */
  async exists(id: number): Promise<boolean> {
    try {
      const result = await this.db.get<{ count: number }>(
        'SELECT COUNT(*) as count FROM orders WHERE order_id = ?',
        [id],
      );
      return (result?.count || 0) > 0;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves all orders placed by a specific branch.
   * 
   * Returns orders sorted by date (most recent first). This method is essential for
   * displaying branch-specific order history, generating branch reports, and
   * analyzing location-based purchasing patterns.
   * 
   * @param branchId - The unique identifier of the branch
   * @returns Promise resolving to an array of orders from the branch
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrdersRepository();
   * const seattleOrders = await repo.findByBranchId(5);
   * console.log(`Seattle branch has ${seattleOrders.length} orders`);
   * seattleOrders.forEach(o => console.log(`- Order #${o.orderId}: ${o.status}`));
   * ```
   */
  async findByBranchId(branchId: number): Promise<Order[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM orders WHERE branch_id = ? ORDER BY order_date DESC',
        [branchId],
      );
      return mapDatabaseRows<Order>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves all orders with a specific status.
   * 
   * Returns orders sorted by date (most recent first). Useful for workflow management,
   * status-based dashboards, and fulfillment tracking. Common statuses include:
   * pending, approved, shipped, delivered, cancelled.
   * 
   * @param status - The order status to filter by
   * @returns Promise resolving to an array of orders with the specified status
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrdersRepository();
   * const pendingOrders = await repo.findByStatus('pending');
   * console.log(`${pendingOrders.length} orders awaiting approval`);
   * // Output: 23 orders awaiting approval
   * ```
   */
  async findByStatus(status: string): Promise<Order[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM orders WHERE status = ? ORDER BY order_date DESC',
        [status],
      );
      return mapDatabaseRows<Order>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves all orders within a specific date range.
   * 
   * Returns orders sorted by date (most recent first). Essential for generating
   * periodic reports, analyzing seasonal trends, and financial reconciliation.
   * Date parameters should be in ISO format (YYYY-MM-DD).
   * 
   * @param startDate - The start of the date range (inclusive, ISO format)
   * @param endDate - The end of the date range (inclusive, ISO format)
   * @returns Promise resolving to an array of orders within the date range
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createOrdersRepository();
   * const januaryOrders = await repo.findByDateRange('2024-01-01', '2024-01-31');
   * console.log(`January had ${januaryOrders.length} orders`);
   * // Output: January had 127 orders
   * ```
   */
  async findByDateRange(startDate: string, endDate: string): Promise<Order[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM orders WHERE order_date >= ? AND order_date <= ? ORDER BY order_date DESC',
        [startDate, endDate],
      );
      return mapDatabaseRows<Order>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }
}

/**
 * Factory function to create a new OrdersRepository instance.
 * 
 * Creates a repository connected to the appropriate database (production or test).
 * Each call creates a new instance; use this when you need isolated repository instances.
 * 
 * @param isTest - Whether to use the test database (default: false)
 * @returns Promise resolving to a new OrdersRepository instance
 * 
 * @example
 * ```typescript
 * // Production usage
 * const repo = await createOrdersRepository();
 * 
 * // Test usage
 * const testRepo = await createOrdersRepository(true);
 * ```
 */
export async function createOrdersRepository(isTest: boolean = false): Promise<OrdersRepository> {
  const db = await getDatabase(isTest);
  return new OrdersRepository(db);
}

// Singleton instance for default usage
let ordersRepo: OrdersRepository | null = null;

/**
 * Retrieves the OrdersRepository instance.
 * 
 * Returns a cached repository instance for production use, or creates a new test instance
 * when in test mode. This provides efficient resource usage by reusing database connections.
 * 
 * @param isTest - Whether to use the test database (default: false)
 * @returns Promise resolving to the OrdersRepository instance
 * 
 * @example
 * ```typescript
 * // Get shared production instance
 * const repo = await getOrdersRepository();
 * 
 * // Get new test instance
 * const testRepo = await getOrdersRepository(true);
 * ```
 */
export async function getOrdersRepository(isTest: boolean = false): Promise<OrdersRepository> {
  const isTestEnv = isTest || process.env.NODE_ENV === 'test' || process.env.VITEST === 'true';
  if (isTestEnv) {
    return createOrdersRepository(true);
  }
  if (!ordersRepo) {
    ordersRepo = await createOrdersRepository(false);
  }
  return ordersRepo;
}
