/**
 * @fileoverview Repository for managing product data access operations.
 * 
 * This module provides data access methods for product entities in the OctoCAT supply chain system.
 * Products represent items available for order from suppliers. Each product belongs to a supplier,
 * has pricing information, stock quantities, and detailed specifications.
 * 
 * The repository implements standard CRUD operations plus specialized queries for:
 * - Finding products by supplier association
 * - Searching products by name patterns
 * - Managing inventory and catalog data
 * - Validating product availability
 * 
 * @module repositories/productsRepo
 */

import { getDatabase, DatabaseConnection } from '../db/sqlite';
import { Product } from '../models/product';
import { handleDatabaseError, NotFoundError } from '../utils/errors';
import { buildInsertSQL, buildUpdateSQL, objectToCamelCase, mapDatabaseRows, DatabaseRow } from '../utils/sql';

export class ProductsRepository {
  private db: DatabaseConnection;

  constructor(db: DatabaseConnection) {
    this.db = db;
  }

  /**
   * Retrieves all products from the database.
   * 
   * Returns products ordered by their unique identifier for consistent pagination
   * and display. This method is commonly used for catalog pages, inventory reports,
   * and administrative product management interfaces.
   * 
   * @returns Promise resolving to an array of all product records
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * const products = await repo.findAll();
   * console.log(`Total products in catalog: ${products.length}`);
   * // Output: Total products in catalog: 247
   * ```
   */
  async findAll(): Promise<Product[]> {
    try {
      const rows = await this.db.all<DatabaseRow>('SELECT * FROM products ORDER BY product_id');
      return mapDatabaseRows<Product>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves a single product by its unique identifier.
   * 
   * Primary lookup method for fetching product details when you have the product ID
   * from an order detail, catalog selection, or URL parameter.
   * 
   * @param id - The unique identifier of the product to retrieve
   * @returns Promise resolving to the product object if found, null otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * const product = await repo.findById(42);
   * if (product) {
   *   console.log(`${product.name}: $${product.price} (${product.stockQuantity} in stock)`);
   *   // Output: Industrial Widget Pro: $299.99 (150 in stock)
   * }
   * ```
   */
  async findById(id: number): Promise<Product | null> {
    try {
      const row = await this.db.get<DatabaseRow>('SELECT * FROM products WHERE product_id = ?', [id]);
      return row ? objectToCamelCase<Product>(row) : null;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Creates a new product in the database.
   * 
   * Inserts a new product record with all required fields including supplier association,
   * pricing, and stock information. The product ID is auto-generated by the database.
   * After creation, the method retrieves and returns the complete product object.
   * 
   * @param product - Product data without the productId (auto-generated)
   * @returns Promise resolving to the newly created product with generated ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If required fields are missing or invalid
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * const newProduct = await repo.create({
   *   supplierId: 5,
   *   name: 'Advanced Circuit Board v2',
   *   description: 'High-performance circuit board with enhanced capabilities',
   *   price: 149.99,
   *   stockQuantity: 200,
   *   sku: 'ACB-V2-2024'
   * });
   * console.log(`Created product: ${newProduct.name} with ID ${newProduct.productId}`);
   * ```
   */
  async create(product: Omit<Product, 'productId'>): Promise<Product> {
    try {
      const { sql, values } = buildInsertSQL('products', product);
      const result = await this.db.run(sql, values);

      const createdProduct = await this.findById(result.lastID || 0);
      if (!createdProduct) {
        throw new Error('Failed to retrieve created product');
      }

      return createdProduct;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Updates an existing product with partial data.
   * 
   * Allows updating specific fields of a product without requiring all fields.
   * Commonly used for price adjustments, stock updates, and description changes.
   * The product ID cannot be modified.
   * 
   * @param id - The unique identifier of the product to update
   * @param product - Partial product data containing only the fields to update
   * @returns Promise resolving to the updated product object
   * @throws {NotFoundError} If no product exists with the given ID
   * @throws {DatabaseError} If the database operation fails
   * @throws {ValidationError} If update data contains invalid values
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * const updated = await repo.update(42, {
   *   price: 279.99,
   *   stockQuantity: 175
   * });
   * console.log(`Updated ${updated.name}: new price $${updated.price}`);
   * ```
   */
  async update(id: number, product: Partial<Omit<Product, 'productId'>>): Promise<Product> {
    try {
      const { sql, values } = buildUpdateSQL('products', product, 'product_id = ?');
      const result = await this.db.run(sql, [...values, id]);

      if (result.changes === 0) {
        throw new NotFoundError('Product', id);
      }

      const updatedProduct = await this.findById(id);
      if (!updatedProduct) {
        throw new Error('Failed to retrieve updated product');
      }

      return updatedProduct;
    } catch (error) {
      handleDatabaseError(error, 'Product', id);
    }
  }

  /**
   * Deletes a product from the database.
   * 
   * Permanently removes the product record. This may fail if the product is referenced
   * in order details due to foreign key constraints. Consider implementing soft deletes
   * or archiving for production use.
   * 
   * @param id - The unique identifier of the product to delete
   * @returns Promise that resolves when deletion is complete
   * @throws {NotFoundError} If no product exists with the given ID
   * @throws {DatabaseError} If deletion fails (e.g., referenced in orders)
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * await repo.delete(999);
   * console.log('Product removed from catalog');
   * ```
   */
  async delete(id: number): Promise<void> {
    try {
      const result = await this.db.run('DELETE FROM products WHERE product_id = ?', [id]);

      if (result.changes === 0) {
        throw new NotFoundError('Product', id);
      }
    } catch (error) {
      handleDatabaseError(error, 'Product', id);
    }
  }

  /**
   * Checks whether a product exists in the database.
   * 
   * Efficient existence check using COUNT query. Useful for validating product
   * references before creating order details or updating inventory.
   * 
   * @param id - The unique identifier of the product to check
   * @returns Promise resolving to true if product exists, false otherwise
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * const productExists = await repo.exists(42);
   * if (!productExists) {
   *   console.log('Product not found, cannot add to order');
   * }
   * ```
   */
  async exists(id: number): Promise<boolean> {
    try {
      const result = await this.db.get<{ count: number }>(
        'SELECT COUNT(*) as count FROM products WHERE product_id = ?',
        [id],
      );
      return (result?.count || 0) > 0;
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Retrieves all products from a specific supplier.
   * 
   * Returns products ordered alphabetically by name. This method is essential for
   * displaying supplier catalogs, managing vendor relationships, and creating
   * supplier-specific order forms.
   * 
   * @param supplierId - The unique identifier of the supplier
   * @returns Promise resolving to an array of products from the supplier
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * const acmeProducts = await repo.findBySupplierId(5);
   * console.log(`ACME Corp offers ${acmeProducts.length} products`);
   * acmeProducts.forEach(p => console.log(`- ${p.name}: $${p.price}`));
   * // Output:
   * // - Advanced Circuit Board v2: $149.99
   * // - Industrial Widget Pro: $299.99
   * ```
   */
  async findBySupplierId(supplierId: number): Promise<Product[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        'SELECT * FROM products WHERE supplier_id = ? ORDER BY name',
        [supplierId],
      );
      return mapDatabaseRows<Product>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Searches for products by name using partial matching.
   * 
   * Performs a case-insensitive LIKE query to find products whose names contain
   * the search term. Results are ordered alphabetically. Useful for search features,
   * autocomplete, and filtering product catalogs.
   * 
   * @param name - Search term to match against product names (case-insensitive)
   * @returns Promise resolving to an array of matching products
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * const widgets = await repo.findByName('Widget');
   * console.log(`Found ${widgets.length} widget products`);
   * // Matches: 'Industrial Widget Pro', 'Widget Assembly Kit', etc.
   * ```
   */
  async findByName(name: string): Promise<Product[]> {
    try {
      const rows = await this.db.all<DatabaseRow>(
        `SELECT * FROM products WHERE name LIKE '%${name}%' ORDER BY name`,
      );
      return mapDatabaseRows<Product>(rows);
    } catch (error) {
      handleDatabaseError(error);
    }
  }

  /**
   * Checks if sufficient stock is available for a product.
   * 
   * Validates that the requested quantity does not exceed the current stock level.
   * This method should be called before adding items to cart (for UI feedback) or
   * during order placement (for strict validation).
   * 
   * @param productId - The unique identifier of the product
   * @param quantity - The quantity to check availability for
   * @returns Promise resolving to true if sufficient stock exists, false otherwise
   * @throws {NotFoundError} If no product exists with the given ID
   * @throws {DatabaseError} If the database query fails
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * const hasStock = await repo.checkStock(42, 10);
   * if (!hasStock) {
   *   console.log('Insufficient stock for order');
   * }
   * ```
   */
  async checkStock(productId: number, quantity: number): Promise<boolean> {
    try {
      const product = await this.findById(productId);
      if (!product) {
        throw new NotFoundError('Product', productId);
      }
      return product.stockLevel >= quantity;
    } catch (error) {
      handleDatabaseError(error, 'Product', productId);
    }
  }

  /**
   * Decrements the stock level of a product by the specified quantity.
   * 
   * This method is transaction-safe and should be called when an order is placed.
   * It will throw an error if the requested quantity exceeds available stock,
   * preventing overselling. Always call checkStock first or use within a transaction.
   * 
   * @param productId - The unique identifier of the product
   * @param quantity - The quantity to decrement from stock
   * @returns Promise that resolves when stock is updated
   * @throws {NotFoundError} If no product exists with the given ID
   * @throws {ValidationError} If quantity exceeds available stock
   * @throws {DatabaseError} If the database operation fails
   * 
   * @example
   * ```typescript
   * const repo = await createProductsRepository();
   * await repo.decrementStock(42, 5);
   * console.log('Stock decremented successfully');
   * ```
   */
  async decrementStock(productId: number, quantity: number): Promise<void> {
    try {
      // First check if we have sufficient stock
      const hasStock = await this.checkStock(productId, quantity);
      if (!hasStock) {
        const product = await this.findById(productId);
        throw new Error(
          `Insufficient stock for product ${product?.name || productId}. ` +
          `Requested: ${quantity}, Available: ${product?.stockLevel || 0}`
        );
      }

      // Decrement the stock
      const result = await this.db.run(
        'UPDATE products SET stock_level = stock_level - ? WHERE product_id = ?',
        [quantity, productId],
      );

      if (result.changes === 0) {
        throw new NotFoundError('Product', productId);
      }
    } catch (error) {
      handleDatabaseError(error, 'Product', productId);
    }
  }
}

/**
 * Factory function to create a new ProductsRepository instance.
 * 
 * Creates a repository connected to the appropriate database (production or test).
 * Each call creates a new instance; use this when you need isolated repository instances.
 * 
 * @param isTest - Whether to use the test database (default: false)
 * @returns Promise resolving to a new ProductsRepository instance
 * 
 * @example
 * ```typescript
 * // Production usage
 * const repo = await createProductsRepository();
 * 
 * // Test usage
 * const testRepo = await createProductsRepository(true);
 * ```
 */
export async function createProductsRepository(
  isTest: boolean = false,
): Promise<ProductsRepository> {
  const db = await getDatabase(isTest);
  return new ProductsRepository(db);
}

// Singleton instance for default usage
let productsRepo: ProductsRepository | null = null;

/**
 * Returns the singleton {@link ProductsRepository} instance, creating it if necessary.
 *
 * Pass `isTest = true` to connect to the test database instead of the shared
 * production instance.
 *
 * @param isTest - Whether to use the test database. Defaults to `false`.
 * @returns A Promise resolving to the {@link ProductsRepository} instance.
 * @example
 * // Production usage — returns (and caches) the shared instance
 * const repo = await getProductsRepository();
 *
 * // Test usage — returns a fresh instance backed by the test database
 * const repo = await getProductsRepository(true);
 */
export async function getProductsRepository(isTest: boolean = false): Promise<ProductsRepository> {
  if (!productsRepo) {
    productsRepo = await createProductsRepository(isTest);
  }
  return productsRepo;
}
